add missing ; to return ()
Without these rustc complains:
```
   Compiling setters v0.1.0 (/home/kalmar/local/rust/100-exercises-to-learn-rust/exercises/03_ticket_v1/07_setters)
error[E0308]: mismatched types
   --> exercises/03_ticket_v1/07_setters/src/lib.rs:110:9
    |
110 | /         Ticket::new(valid_title(), valid_description(), "To-Do".into())
111 | |             .set_title(overly_long_title())
    | |___________________________________________^ expected `()`, found `&Ticket`
    |
help: consider using a semicolon here
    |
111 |             .set_title(overly_long_title());
    |                                            +
help: try adding a return type
    |
109 |     fn title_cannot_be_longer_than_fifty_chars() -> &Ticket {
    |                                                  ++++++++++

For more information about this error, try `rustc --explain E0308`.
error: could not compile `setters` (lib test) due to 1 previous error
```